### ISSUE TITLE
How to add rethinkdb or other database 

### ISSUE THREAD

**Issue by panigrah** [Codigami/hapi-starter-kit#4]
Hi,
I am trying to figure out the best way to add rethinkdb to this boiler plate. I am using hapi-rethinkdb which binds `rethinkdb` and `connection` to the server context in a request per this documentation.

https://github.com/ghostbar/hapi-rethinkdb#use-plugin

But in this boilerplate this context is not available in the handlers. So how do I setup the handlers on this starter kit so that `this.rethinkdb` is available in the handler?

I am having to instead use `var r = request.server.plugins['hapi-rethinkdb'].rethinkdb` to get a connection to the rethink db in every time in each handler.

thanks,

**Comment by kunalkapadia** [comment]
@panigrah Ideally `this` context should be available in handlers. Can you let me know what error do you get when you try to use `this` context in the handlers?

**Comment by panigrah** [comment]
@KunalKapadia it says `this.rethinkdb` is null.

**Comment by kunalkapadia** [comment]
@panigrah I am not sure about `this.rethinkdb` but `this` context should be available in the handlers. May be you can raise an issue in `rethinkdb` repo if `this.rethinkdb` is not being set.

**Comment by panigrah** [comment]
@KunalKapadia will reopen if I figure out a solution. thanks for the pointers.
